server:
  port: 8080

secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: joseonpaldo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    
    show-sql: true
    database: mysql 
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - profile
              - email
            redirect-uri: "https://joseonpaldo.site/api/login/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "https://joseonpaldo.site/api/login/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_CLIENT_ID}  
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email
              - profile_image
            redirect-uri: "https://joseonpaldo.site/api/login/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # "인가 코드 받기" 항목
            token-uri: https://nid.naver.com/oauth2.0/token # "토큰 받기" 항목
            user-info-uri: https://openapi.naver.com/v1/nid/me # "사용자 정보 가져오기" 항목
            user-name-attribute: response # 식별자 . 카카오의 경우 "id" 사용