server:
  port: 8080
  
spring:
  application:
    name: joseonpaldo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://(dbip)/(dbschema)?serverTimezone=Asia/Seoul
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    
    show-sql: true
    database: mysql 
    database-platform: org.hibernate.dialect.MySQLDialect
