name: Gradle Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Verify Java version
      run: java -version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew build --info
      env: 
        DB_URL: ${{ secret.DB_URL }}
        DB_USERNAME: ${{ secret.DB_USERNAME }}
        DB_PASSWORD: ${{ secret.DB_PASSWORD }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:${{ github.sha }}

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:${{ github.sha }}
          docker stop spring-boot-app || true
          docker rm spring-boot-app || true
          docker run -d -p 80:8080 --name spring-boot-app ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:${{ github.sha }}
